name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
defaults:
  run:
    working-directory: ./rdicidr-0.1.0
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v5
    - name: npm install
      run: npm install
    - name: npm run lint
      run: npm run lint
    - name: CI=true npm run test
      run: CI=true npm run test
    - name: npm run build
      run: npm run build
