name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    branches:
    - main
    - dev
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    - name: Check out repository code
      uses: actions/checkout@v5
    
    - name: Set the node version to 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install

    - name: Run Linter (ESLint)
      run: npm run lint

    - name: Run Test (Jest)
      run: CI=true npm run test

    - name: Run Build
      run: npm run build

  